name: Android UI Test Suites

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

env:
  ALLURE_VERSION: 2.41.0

jobs:

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Enable Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo chmod 666 /dev/kvm

      - name: Run Smoke Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: >
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -camera-back none
            -no-snapshot
            -no-metrics
          emulator-boot-timeout: 900
          script: |
            adb wait-for-device
            sleep 60            
            ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.convapp.tests.SmokeTests

#      - name: Debug Allure Files
#        if: always()
#        run: |
#          echo "===== SEARCHING ALLURE FILES ====="
#          find . -type d -name "allure-results"
#          find . -type f | grep allure || true

      - name: Upload Smoke Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: |
            app/build/reports/
            app/build/outputs/androidTest-results/
            app/build/outputs/connected_android_test_additional_output/
          if-no-files-found: error

      - name: Upload Smoke Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-failure-screenshots
          path: |
            **/test-screenshots/**
            **/*.png

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Enable Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo chmod 666 /dev/kvm

      - name: Clear previous Allure results
        run: rm -rf app/build/allure-results

      - name: Run Functional Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: >
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -camera-back none
            -no-snapshot
            -no-metrics
          emulator-boot-timeout: 900
          script: |
            adb wait-for-device
            sleep 60            
            ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.convapp.tests.FunctionalTests

#      - name: Debug Allure Files
#        if: always()
#        run: |
#          echo "===== SEARCHING ALLURE FILES ====="
#          find . -type d -name "allure-results"
#          find . -type f | grep allure || true

      - name: Upload Functional Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-functional
          path: |
            app/build/reports/
            app/build/outputs/androidTest-results/
            app/build/outputs/connected_android_test_additional_output/
          if-no-files-found: error

      - name: Upload Functional Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-failure-screenshots
          path: |
            **/test-screenshots/**
            **/*.png

  edge-tests:
    name: Edge Case Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Enable Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo chmod 666 /dev/kvm

      - name: Clear previous Allure results
        run: rm -rf app/build/allure-results

      - name: Run Edge Case Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: >
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -camera-back none
            -no-snapshot
            -no-metrics
          emulator-boot-timeout: 900
          script: |
            adb wait-for-device
            sleep 60
            ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.convapp.tests.EdgeCaseTests

#      - name: Debug Allure Files
#        if: always()
#        run: |
#          echo "===== SEARCHING ALLURE FILES ====="
#          find . -type d -name "allure-results"
#          find . -type f | grep allure || true

      - name: Upload Edge Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-edge
          path: |
            app/build/reports/
            app/build/outputs/androidTest-results/
            app/build/outputs/connected_android_test_additional_output/
          if-no-files-found: error

      - name: Upload Edge Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: edge-failure-screenshots
          path: |
            **/test-screenshots/**
            **/*.png

  publish-allure:
    name: Publish Allure Report
    runs-on: ubuntu-latest
    needs:
      - smoke-tests
      - functional-tests
      - edge-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Smoke Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-smoke
          path: merged-results/smoke

      - name: Download Functional Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-functional
          path: merged-results/functional

      - name: Download Edge Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-edge
          path: merged-results/edge

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          tar -zxvf allure-${ALLURE_VERSION}.tgz
          sudo mv allure-${ALLURE_VERSION} /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Merge Allure Results
        run: |
#          mkdir merged-results
          cp -r allure-results/smoke/* merged-results/ || true
          cp -r allure-results/functional/* merged-results/ || true
          cp -r allure-results/edge/* merged-results/ || true

      - name: Generate Allure Report
        run: allure generate merged-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report